// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Question interface {
	IsQuestion()
}

type Answer struct {
	QuestionID string  `json:"questionId"`
	Body       string  `json:"body"`
	Weight     float64 `json:"weight"`
}

type ChoiceQuestion struct {
	ID      string    `json:"id"`
	Body    string    `json:"body"`
	Weight  float64   `json:"weight"`
	Options []*Option `json:"options"`
}

func (ChoiceQuestion) IsQuestion() {}

type NewAnswer struct {
	QuestionID string  `json:"questionID"`
	OptionID   *string `json:"optionID"`
	Body       *string `json:"body"`
}

type Option struct {
	ID     string  `json:"id"`
	Body   string  `json:"body"`
	Weight float64 `json:"weight"`
}

type Result struct {
	Weight float64 `json:"weight"`
}

type TextQuestion struct {
	ID     string  `json:"id"`
	Body   string  `json:"body"`
	Weight float64 `json:"weight"`
}

func (TextQuestion) IsQuestion() {}
